# ~/.config/mpv/input.conf

#ENTER seek 1 absolute ; set glsl-shaders ""

# next W
#W quit #seek 100 absolute-percent
#, quit #seek 100 absolute-percent
# previous S
#S seek 0 absolute-percent # go to beginning
#o seek 0 absolute-percent # go to beginning

# vol up A a
#A add volume 5
a add volume 5
d add volume -5

a add volume 5
e add volume -5

KP_INS seek 0 absolute-percent # go to beginning
0 seek 0 absolute-percent # go to beginning

# arrow keys signal direction to charlietv via exit code
RIGHT quit 4
LEFT quit 3

UP seek 10
DOWN seek -5

# Q quits
' quit 5 #seek 100 absolute-percent
q quit 5 #seek 100 absolute-percent

# I information
i show-text "Controls: \n (q) quit, (←) previous channel, (→) next channel \n (f) fullscreen, (r) resize screen \n (7) and (9) to jump chapters \n (4) and (6) to jump episodes \n (5) cycle filters \n (k) to keep the file, (delete) to remove the file \n (0) to restart episode, (enter) skip to next episode \n" 20000
c show-text "Controls: \n (q) quit, (←) previous channel, (→) next channel \n (f) fullscreen, (r) resize screen \n (7) and (9) to jump chapters \n (4) and (6) to jump episodes \n (5) cycle filters \n (k) to keep the file, (delete) to remove the file \n (0) to restart episode, (enter) skip to next episode \n" 20000

; cycle-values glsl-shaders "Default" "NoChroma.hook" "crt-gdv-mini-ultra-trinitron.glsl"  "crt-hyllian.glsl" "crt-lottes.glsl" "crt-royale-kurozumi.glsl"
#' cycle pause
#D add volume -5
#e add volume -5
#E add volume -5

BS quit #seek 100 absolute-percent    # Jump to end
KP_DEL quit #seek 100 absolute-percent    # Jump to end
KP_DEC quit #seek 100 absolute-percent    # Jump to end

DEL quit 6    # Delete current file (handled by charlietv2.sh)

k quit 7      # Move to Movies if in New (handled by charlietv2.sh)
t quit 7      # Move to Movies if in New (handled by charlietv2.sh)

r set fullscreen no ; set geometry 50%+0+0
p set fullscreen no ; set geometry 50%+0+0

f set fullscreen yes
u set fullscreen yes

#y script-binding nextfile
#t script-binding cycle-through-existing


KP5 cycle-values glsl-shaders "Default" "NoChroma.hook" "crt-gdv-mini-ultra-trinitron.glsl"  "crt-hyllian.glsl" "crt-lottes.glsl" "crt-royale-kurozumi.glsl"
KP0 seek 0 absolute-percent

KP4 script-binding previousfile #; seek 0 absolute-percent # TODO - also go to the start
KP6 script-binding nextfile #; seek 0 absolute-percent #_and_rewind # TODO - also go to the start
KP_ENTER script-binding nextfile

KP7 add chapter -1
KP9 add chapter 1

# Space: toggle pause AND clear any active GLSL shaders
#SPACE cycle pause ; set glsl-shaders ""
#SPACE cycle pause ; cycle-values glsl-shaders "" "NoChroma.hook"
#ESC quit 5

