# ~/.config/mpv/input.conf

a        add volume 5
e        add volume -5

a        add volume 5
d        add volume -5

UP       add volume 5
DOWN     add volume -5

KP5      cycle-values glsl-shaders "Default" "NoChroma.hook" "crt-gdv-mini-ultra-trinitron.glsl"  "crt-hyllian.glsl" "crt-lottes.glsl" "crt-royale-kurozumi.glsl"

KP7      add chapter -1
KP9      add chapter  1

KP4      script-binding previousfile
KP6      script-binding nextfile

KP1      seek -5
KP3      seek 10

BS       quit
KP_DEL   quit
KP_DEC   quit

# Change channels
LEFT     quit 3
o        quit 3
w        quit 3

RIGHT    quit 4
,        quit 4
s        quit 4

# Close
ESC      quit 5
'        quit 5
q        quit 5

# Delete current file
DEL      quit 6

# Move New file to Movies
k        quit 7
t        quit 7

# Restart file
KP_INS   seek 0.25 absolute-percent ; show-text "Let's get restarted in here"
KP0      seek 0.25 absolute-percent ; show-text "Let's get restarted in here"
-        seek 0.25 absolute-percent ; show-text "Let's get restarted in here"
0        seek 0.25 absolute-percent ; show-text "Let's get restarted in here"

# Jump to next episode
ENTER    script-binding nextfile
KP_ENTER script-binding nextfile
s        script-binding nextfile

# Pause
SPACE    cycle pause ; no-osd cycle-values glsl-shaders "NoChroma.hook" "Default" ; script-message toggle-info
y        cycle pause ; no-osd cycle-values glsl-shaders "NoChroma.hook" "Default" ; script-message toggle-info

# Toggle fullscreen
f        cycle fullscreen ; no-osd set geometry 50%+0+0
u        cycle fullscreen ; no-osd set geometry 50%+0+0





