[norm]
profile-desc="Normalize audio volume"
af=lavfi=[loudnorm=I=-16:TP=-3:LRA=4]

#osd-playing-msg = "${filename}"


# I like a subtle progress bar at all times; see scripts/progress-bar-always.lua
#osd-bar-align-y=1 # bottom
#osd-bar-w=100     # full width
#osd-bar-h=0.2     # subtle, 0.2% of screen height
#osd-msg3=" "      # don't show time/percentage; use OSC for that
#osd-back-color="#000000"
#osd-color="#ffffff"
# I wish osd-bar-border-size=0 worked
#
# # Enables saving of playback position and other metadata
#save-position-on-quit=yes

# REQUIRED: Tell mpv specifically which window properties to save
# This will save the window size, position, and fullscreen state
#watch-later-options=fullscreen,geometry,window-scale,window-maximized

# Prevents the window from snapping back to video resolution on new files
#auto-window-resize=no

# Optional: ensures your window doesn't go off-screen if you use multiple monitors
# write-filename-in-watch-later-config=yes
